[2022-03-15 09:50:58,967] {processor.py:163} INFO - Started process (PID=1149) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:50:58,968] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:50:58,969] {logging_mixin.py:109} INFO - [2022-03-15 09:50:58,969] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:50:58,971] {logging_mixin.py:109} INFO - [2022-03-15 09:50:58,970] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:50:58,981] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:50:58,994] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 09:51:29,703] {processor.py:163} INFO - Started process (PID=1211) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:51:29,704] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:51:29,705] {logging_mixin.py:109} INFO - [2022-03-15 09:51:29,705] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:51:29,707] {logging_mixin.py:109} INFO - [2022-03-15 09:51:29,707] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:51:29,719] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:51:29,732] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.031 seconds
[2022-03-15 09:52:00,490] {processor.py:163} INFO - Started process (PID=1264) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:52:00,491] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:52:00,491] {logging_mixin.py:109} INFO - [2022-03-15 09:52:00,491] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:52:00,493] {logging_mixin.py:109} INFO - [2022-03-15 09:52:00,493] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:52:00,504] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:52:00,517] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 09:52:31,250] {processor.py:163} INFO - Started process (PID=1326) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:52:31,251] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:52:31,252] {logging_mixin.py:109} INFO - [2022-03-15 09:52:31,252] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:52:31,253] {logging_mixin.py:109} INFO - [2022-03-15 09:52:31,253] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:52:31,263] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:52:31,276] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.028 seconds
[2022-03-15 09:53:01,964] {processor.py:163} INFO - Started process (PID=1379) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:53:01,966] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:53:01,966] {logging_mixin.py:109} INFO - [2022-03-15 09:53:01,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:53:01,968] {logging_mixin.py:109} INFO - [2022-03-15 09:53:01,968] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:53:01,981] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:53:01,989] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.026 seconds
[2022-03-15 09:53:32,850] {processor.py:163} INFO - Started process (PID=1441) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:53:32,851] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:53:32,851] {logging_mixin.py:109} INFO - [2022-03-15 09:53:32,851] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:53:32,853] {logging_mixin.py:109} INFO - [2022-03-15 09:53:32,852] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:53:32,863] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:53:32,876] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.028 seconds
[2022-03-15 09:54:03,617] {processor.py:163} INFO - Started process (PID=1494) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:54:03,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:54:03,619] {logging_mixin.py:109} INFO - [2022-03-15 09:54:03,619] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:54:03,621] {logging_mixin.py:109} INFO - [2022-03-15 09:54:03,620] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:54:03,633] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:54:03,646] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.031 seconds
[2022-03-15 09:54:33,888] {processor.py:163} INFO - Started process (PID=1556) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:54:33,889] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:54:33,889] {logging_mixin.py:109} INFO - [2022-03-15 09:54:33,889] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:54:33,891] {logging_mixin.py:109} INFO - [2022-03-15 09:54:33,890] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:54:33,902] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:54:33,916] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.030 seconds
[2022-03-15 09:55:04,047] {processor.py:163} INFO - Started process (PID=1610) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:55:04,049] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:55:04,049] {logging_mixin.py:109} INFO - [2022-03-15 09:55:04,049] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:55:04,051] {logging_mixin.py:109} INFO - [2022-03-15 09:55:04,050] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:55:04,062] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:55:04,074] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.030 seconds
[2022-03-15 09:55:34,901] {processor.py:163} INFO - Started process (PID=1664) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:55:34,902] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:55:34,902] {logging_mixin.py:109} INFO - [2022-03-15 09:55:34,902] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:55:34,904] {logging_mixin.py:109} INFO - [2022-03-15 09:55:34,904] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:55:34,917] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:55:34,929] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.031 seconds
[2022-03-15 09:56:05,102] {processor.py:163} INFO - Started process (PID=1726) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:56:05,103] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:56:05,104] {logging_mixin.py:109} INFO - [2022-03-15 09:56:05,104] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:56:05,106] {logging_mixin.py:109} INFO - [2022-03-15 09:56:05,105] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:56:05,116] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:56:05,129] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 09:56:35,235] {processor.py:163} INFO - Started process (PID=1780) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:56:35,236] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:56:35,237] {logging_mixin.py:109} INFO - [2022-03-15 09:56:35,237] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:56:35,239] {logging_mixin.py:109} INFO - [2022-03-15 09:56:35,238] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:56:35,253] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:56:35,266] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.034 seconds
[2022-03-15 09:57:05,328] {processor.py:163} INFO - Started process (PID=1843) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:57:05,330] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:57:05,330] {logging_mixin.py:109} INFO - [2022-03-15 09:57:05,330] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:57:05,332] {logging_mixin.py:109} INFO - [2022-03-15 09:57:05,331] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:57:05,344] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:57:05,361] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.035 seconds
[2022-03-15 09:57:36,136] {processor.py:163} INFO - Started process (PID=1896) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:57:36,137] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:57:36,137] {logging_mixin.py:109} INFO - [2022-03-15 09:57:36,137] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:57:36,139] {logging_mixin.py:109} INFO - [2022-03-15 09:57:36,139] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:57:36,152] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:57:36,165] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.031 seconds
[2022-03-15 09:58:07,127] {processor.py:163} INFO - Started process (PID=1958) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:07,128] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:58:07,128] {logging_mixin.py:109} INFO - [2022-03-15 09:58:07,128] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:07,130] {logging_mixin.py:109} INFO - [2022-03-15 09:58:07,130] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:58:07,143] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:07,156] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.032 seconds
[2022-03-15 09:58:23,520] {processor.py:163} INFO - Started process (PID=1976) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:23,521] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:58:23,521] {logging_mixin.py:109} INFO - [2022-03-15 09:58:23,521] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:23,524] {logging_mixin.py:109} INFO - [2022-03-15 09:58:23,523] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:58:23,536] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:23,556] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.038 seconds
[2022-03-15 09:58:54,290] {processor.py:163} INFO - Started process (PID=2029) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:54,292] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:58:54,292] {logging_mixin.py:109} INFO - [2022-03-15 09:58:54,292] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:54,294] {logging_mixin.py:109} INFO - [2022-03-15 09:58:54,294] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:58:54,306] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:58:54,314] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.026 seconds
[2022-03-15 09:59:25,004] {processor.py:163} INFO - Started process (PID=2091) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:59:25,005] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:59:25,005] {logging_mixin.py:109} INFO - [2022-03-15 09:59:25,005] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:59:25,007] {logging_mixin.py:109} INFO - [2022-03-15 09:59:25,007] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:59:25,019] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:59:25,039] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.037 seconds
[2022-03-15 09:59:55,825] {processor.py:163} INFO - Started process (PID=2144) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:59:55,827] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 09:59:55,828] {logging_mixin.py:109} INFO - [2022-03-15 09:59:55,828] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:59:55,830] {logging_mixin.py:109} INFO - [2022-03-15 09:59:55,829] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 09:59:55,844] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 09:59:55,853] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.030 seconds
[2022-03-15 10:00:26,762] {processor.py:163} INFO - Started process (PID=2208) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:00:26,763] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:00:26,763] {logging_mixin.py:109} INFO - [2022-03-15 10:00:26,763] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:00:26,765] {logging_mixin.py:109} INFO - [2022-03-15 10:00:26,764] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:00:26,779] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:00:26,794] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.034 seconds
[2022-03-15 10:00:57,521] {processor.py:163} INFO - Started process (PID=2261) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:00:57,522] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:00:57,523] {logging_mixin.py:109} INFO - [2022-03-15 10:00:57,522] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:00:57,525] {logging_mixin.py:109} INFO - [2022-03-15 10:00:57,524] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:00:57,537] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:00:57,549] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.030 seconds
[2022-03-15 10:01:27,805] {processor.py:163} INFO - Started process (PID=2315) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:01:27,806] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:01:27,806] {logging_mixin.py:109} INFO - [2022-03-15 10:01:27,806] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:01:27,808] {logging_mixin.py:109} INFO - [2022-03-15 10:01:27,808] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:01:27,821] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:01:27,835] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.032 seconds
[2022-03-15 10:01:58,012] {processor.py:163} INFO - Started process (PID=2380) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:01:58,013] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:01:58,014] {logging_mixin.py:109} INFO - [2022-03-15 10:01:58,014] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:01:58,016] {logging_mixin.py:109} INFO - [2022-03-15 10:01:58,015] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:01:58,027] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:01:58,040] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.030 seconds
[2022-03-15 10:02:14,508] {processor.py:163} INFO - Started process (PID=2416) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:02:14,509] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:02:14,509] {logging_mixin.py:109} INFO - [2022-03-15 10:02:14,509] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:02:14,511] {logging_mixin.py:109} INFO - [2022-03-15 10:02:14,511] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:02:14,548] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:02:14,562] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.056 seconds
[2022-03-15 10:02:45,373] {processor.py:163} INFO - Started process (PID=2471) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:02:45,374] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:02:45,375] {logging_mixin.py:109} INFO - [2022-03-15 10:02:45,375] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:02:45,377] {logging_mixin.py:109} INFO - [2022-03-15 10:02:45,376] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:02:45,419] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:02:45,436] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.066 seconds
[2022-03-15 10:03:16,201] {processor.py:163} INFO - Started process (PID=2533) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:03:16,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:03:16,202] {logging_mixin.py:109} INFO - [2022-03-15 10:03:16,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:03:16,204] {logging_mixin.py:109} INFO - [2022-03-15 10:03:16,203] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:03:16,217] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:03:16,230] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.031 seconds
[2022-03-15 10:03:46,297] {processor.py:163} INFO - Started process (PID=2586) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:03:46,299] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:03:46,299] {logging_mixin.py:109} INFO - [2022-03-15 10:03:46,299] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:03:46,301] {logging_mixin.py:109} INFO - [2022-03-15 10:03:46,300] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:03:46,314] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:03:46,327] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.032 seconds
[2022-03-15 10:04:17,012] {processor.py:163} INFO - Started process (PID=2649) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:04:17,012] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:04:17,013] {logging_mixin.py:109} INFO - [2022-03-15 10:04:17,013] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:04:17,015] {logging_mixin.py:109} INFO - [2022-03-15 10:04:17,014] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:04:17,027] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:04:17,040] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.031 seconds
[2022-03-15 10:04:47,127] {processor.py:163} INFO - Started process (PID=2702) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:04:47,128] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:04:47,129] {logging_mixin.py:109} INFO - [2022-03-15 10:04:47,129] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:04:47,130] {logging_mixin.py:109} INFO - [2022-03-15 10:04:47,130] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:04:47,141] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:04:47,148] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.023 seconds
[2022-03-15 10:05:17,882] {processor.py:163} INFO - Started process (PID=2764) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:05:17,883] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:05:17,883] {logging_mixin.py:109} INFO - [2022-03-15 10:05:17,883] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:05:17,885] {logging_mixin.py:109} INFO - [2022-03-15 10:05:17,884] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:05:17,896] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:05:17,903] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.023 seconds
[2022-03-15 10:05:48,557] {processor.py:163} INFO - Started process (PID=2817) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:05:48,559] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:05:48,559] {logging_mixin.py:109} INFO - [2022-03-15 10:05:48,559] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:05:48,561] {logging_mixin.py:109} INFO - [2022-03-15 10:05:48,560] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:05:48,571] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:05:48,578] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.023 seconds
[2022-03-15 10:06:18,782] {processor.py:163} INFO - Started process (PID=2870) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:06:18,783] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:06:18,784] {logging_mixin.py:109} INFO - [2022-03-15 10:06:18,783] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:06:18,786] {logging_mixin.py:109} INFO - [2022-03-15 10:06:18,785] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:06:18,802] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:06:18,817] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.037 seconds
[2022-03-15 10:11:50,106] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:11:50,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:11:50,109] {logging_mixin.py:109} INFO - [2022-03-15 10:11:50,109] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:11:50,112] {logging_mixin.py:109} INFO - [2022-03-15 10:11:50,111] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:11:50,130] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:11:50,148] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.044 seconds
[2022-03-15 10:12:20,717] {processor.py:163} INFO - Started process (PID=93) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:12:20,718] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:12:20,718] {logging_mixin.py:109} INFO - [2022-03-15 10:12:20,718] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:12:20,720] {logging_mixin.py:109} INFO - [2022-03-15 10:12:20,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:12:20,730] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:12:20,743] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 10:12:51,534] {processor.py:163} INFO - Started process (PID=156) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:12:51,535] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:12:51,535] {logging_mixin.py:109} INFO - [2022-03-15 10:12:51,535] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:12:51,537] {logging_mixin.py:109} INFO - [2022-03-15 10:12:51,536] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:12:51,550] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:12:51,558] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.027 seconds
[2022-03-15 10:13:21,578] {processor.py:163} INFO - Started process (PID=210) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:13:21,578] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:13:21,579] {logging_mixin.py:109} INFO - [2022-03-15 10:13:21,579] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:13:21,580] {logging_mixin.py:109} INFO - [2022-03-15 10:13:21,580] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:13:21,592] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:13:21,604] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 10:13:52,549] {processor.py:163} INFO - Started process (PID=272) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:13:52,550] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:13:52,550] {logging_mixin.py:109} INFO - [2022-03-15 10:13:52,550] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:13:52,552] {logging_mixin.py:109} INFO - [2022-03-15 10:13:52,552] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:13:52,563] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:13:52,570] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.023 seconds
[2022-03-15 10:14:23,330] {processor.py:163} INFO - Started process (PID=325) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:14:23,331] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:14:23,331] {logging_mixin.py:109} INFO - [2022-03-15 10:14:23,331] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:14:23,333] {logging_mixin.py:109} INFO - [2022-03-15 10:14:23,332] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:14:23,344] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:14:23,356] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 10:14:54,150] {processor.py:163} INFO - Started process (PID=378) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:14:54,152] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:14:54,152] {logging_mixin.py:109} INFO - [2022-03-15 10:14:54,152] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:14:54,155] {logging_mixin.py:109} INFO - [2022-03-15 10:14:54,154] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:14:54,168] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:14:54,182] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.034 seconds
[2022-03-15 10:15:24,361] {processor.py:163} INFO - Started process (PID=440) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:15:24,362] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:15:24,363] {logging_mixin.py:109} INFO - [2022-03-15 10:15:24,362] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:15:24,364] {logging_mixin.py:109} INFO - [2022-03-15 10:15:24,364] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:15:24,375] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:15:24,388] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 10:15:54,595] {processor.py:163} INFO - Started process (PID=494) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:15:54,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:15:54,597] {logging_mixin.py:109} INFO - [2022-03-15 10:15:54,597] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:15:54,599] {logging_mixin.py:109} INFO - [2022-03-15 10:15:54,599] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:15:54,611] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:15:54,623] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.030 seconds
[2022-03-15 10:16:24,706] {processor.py:163} INFO - Started process (PID=556) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:16:24,706] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:16:24,707] {logging_mixin.py:109} INFO - [2022-03-15 10:16:24,707] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:16:24,709] {logging_mixin.py:109} INFO - [2022-03-15 10:16:24,708] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/load_snowflake.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_snowflake.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2022-03-15 10:16:24,719] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:16:24,732] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.029 seconds
[2022-03-15 10:18:28,090] {processor.py:163} INFO - Started process (PID=39) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:18:28,094] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:18:28,095] {logging_mixin.py:109} INFO - [2022-03-15 10:18:28,095] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:18:30,003] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:18:30,955] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:18:33,592] {logging_mixin.py:109} INFO - [2022-03-15 10:18:33,592] {manager.py:496} INFO - Created Permission View: can read on DAG:example_snowflake
[2022-03-15 10:18:33,605] {logging_mixin.py:109} INFO - [2022-03-15 10:18:33,605] {manager.py:496} INFO - Created Permission View: can edit on DAG:example_snowflake
[2022-03-15 10:18:33,606] {logging_mixin.py:109} INFO - [2022-03-15 10:18:33,605] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:18:33,613] {logging_mixin.py:109} INFO - [2022-03-15 10:18:33,613] {dag.py:2417} INFO - Creating ORM DAG for example_snowflake
[2022-03-15 10:18:33,619] {logging_mixin.py:109} INFO - [2022-03-15 10:18:33,619] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:18:33.619221+00:00
[2022-03-15 10:18:33,637] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 5.549 seconds
[2022-03-15 10:19:03,822] {processor.py:163} INFO - Started process (PID=142) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:19:03,823] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:19:03,824] {logging_mixin.py:109} INFO - [2022-03-15 10:19:03,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:19:04,342] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:19:04,615] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:19:04,621] {logging_mixin.py:109} INFO - [2022-03-15 10:19:04,621] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:19:04,634] {logging_mixin.py:109} INFO - [2022-03-15 10:19:04,634] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:19:04.634025+00:00
[2022-03-15 10:19:04,643] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.823 seconds
[2022-03-15 10:19:35,010] {processor.py:163} INFO - Started process (PID=204) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:19:35,012] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:19:35,013] {logging_mixin.py:109} INFO - [2022-03-15 10:19:35,012] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:19:35,529] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:19:35,773] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:19:35,779] {logging_mixin.py:109} INFO - [2022-03-15 10:19:35,778] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:19:35,788] {logging_mixin.py:109} INFO - [2022-03-15 10:19:35,788] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:19:35.788682+00:00
[2022-03-15 10:19:35,802] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.794 seconds
[2022-03-15 10:20:05,925] {processor.py:163} INFO - Started process (PID=273) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:20:05,926] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:20:05,927] {logging_mixin.py:109} INFO - [2022-03-15 10:20:05,926] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:20:06,469] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:20:06,734] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:20:06,740] {logging_mixin.py:109} INFO - [2022-03-15 10:20:06,740] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:20:06,751] {logging_mixin.py:109} INFO - [2022-03-15 10:20:06,751] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:20:06.751271+00:00
[2022-03-15 10:20:06,765] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.842 seconds
[2022-03-15 10:20:37,433] {processor.py:163} INFO - Started process (PID=340) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:20:37,434] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:20:37,434] {logging_mixin.py:109} INFO - [2022-03-15 10:20:37,434] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:20:37,931] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:20:38,179] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:20:38,185] {logging_mixin.py:109} INFO - [2022-03-15 10:20:38,184] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:20:38,195] {logging_mixin.py:109} INFO - [2022-03-15 10:20:38,194] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:20:38.194832+00:00
[2022-03-15 10:20:38,202] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.772 seconds
[2022-03-15 10:21:08,902] {processor.py:163} INFO - Started process (PID=411) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:21:08,903] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:21:08,903] {logging_mixin.py:109} INFO - [2022-03-15 10:21:08,903] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:21:09,425] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:21:09,681] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:21:09,687] {logging_mixin.py:109} INFO - [2022-03-15 10:21:09,687] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:21:09,698] {logging_mixin.py:109} INFO - [2022-03-15 10:21:09,698] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:21:09.698331+00:00
[2022-03-15 10:21:09,706] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.806 seconds
[2022-03-15 10:21:40,435] {processor.py:163} INFO - Started process (PID=473) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:21:40,436] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:21:40,436] {logging_mixin.py:109} INFO - [2022-03-15 10:21:40,436] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:21:40,935] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:21:41,206] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:21:41,212] {logging_mixin.py:109} INFO - [2022-03-15 10:21:41,211] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:21:41,221] {logging_mixin.py:109} INFO - [2022-03-15 10:21:41,221] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:21:41.221756+00:00
[2022-03-15 10:21:41,234] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.802 seconds
[2022-03-15 10:22:11,853] {processor.py:163} INFO - Started process (PID=544) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:22:11,854] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:22:11,854] {logging_mixin.py:109} INFO - [2022-03-15 10:22:11,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:22:12,362] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:22:12,625] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:22:12,632] {logging_mixin.py:109} INFO - [2022-03-15 10:22:12,632] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:22:12,644] {logging_mixin.py:109} INFO - [2022-03-15 10:22:12,644] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:22:12.643833+00:00
[2022-03-15 10:22:12,658] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.807 seconds
[2022-03-15 10:22:42,695] {processor.py:163} INFO - Started process (PID=606) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:22:42,697] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:22:42,697] {logging_mixin.py:109} INFO - [2022-03-15 10:22:42,697] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:22:43,176] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:22:43,422] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:22:43,428] {logging_mixin.py:109} INFO - [2022-03-15 10:22:43,427] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:22:43,437] {logging_mixin.py:109} INFO - [2022-03-15 10:22:43,437] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:22:43.437782+00:00
[2022-03-15 10:22:43,451] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.758 seconds
[2022-03-15 10:23:14,063] {processor.py:163} INFO - Started process (PID=677) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:23:14,065] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:23:14,065] {logging_mixin.py:109} INFO - [2022-03-15 10:23:14,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:23:14,583] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:23:14,834] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:23:14,841] {logging_mixin.py:109} INFO - [2022-03-15 10:23:14,840] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:23:14,852] {logging_mixin.py:109} INFO - [2022-03-15 10:23:14,852] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:23:14.852583+00:00
[2022-03-15 10:23:14,873] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.811 seconds
[2022-03-15 10:23:45,651] {processor.py:163} INFO - Started process (PID=747) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:23:45,652] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:23:45,652] {logging_mixin.py:109} INFO - [2022-03-15 10:23:45,652] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:23:46,123] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:23:46,370] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:23:46,376] {logging_mixin.py:109} INFO - [2022-03-15 10:23:46,376] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:23:46,387] {logging_mixin.py:109} INFO - [2022-03-15 10:23:46,387] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:23:46.387165+00:00
[2022-03-15 10:23:46,401] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.751 seconds
[2022-03-15 10:24:17,109] {processor.py:163} INFO - Started process (PID=818) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:24:17,110] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:24:17,110] {logging_mixin.py:109} INFO - [2022-03-15 10:24:17,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:24:17,679] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:24:17,945] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:24:17,951] {logging_mixin.py:109} INFO - [2022-03-15 10:24:17,951] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:24:17,962] {logging_mixin.py:109} INFO - [2022-03-15 10:24:17,961] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:24:17.961799+00:00
[2022-03-15 10:24:17,975] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.868 seconds
[2022-03-15 10:24:48,737] {processor.py:163} INFO - Started process (PID=880) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:24:48,738] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:24:48,738] {logging_mixin.py:109} INFO - [2022-03-15 10:24:48,738] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:24:49,215] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:24:49,478] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:24:49,485] {logging_mixin.py:109} INFO - [2022-03-15 10:24:49,484] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:24:49,496] {logging_mixin.py:109} INFO - [2022-03-15 10:24:49,496] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:24:49.495872+00:00
[2022-03-15 10:24:49,503] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.768 seconds
[2022-03-15 10:25:19,540] {processor.py:163} INFO - Started process (PID=951) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:25:19,542] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:25:19,543] {logging_mixin.py:109} INFO - [2022-03-15 10:25:19,542] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:25:20,051] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:25:20,311] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:25:20,317] {logging_mixin.py:109} INFO - [2022-03-15 10:25:20,317] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:25:20,329] {logging_mixin.py:109} INFO - [2022-03-15 10:25:20,329] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-14T10:25:20.328941+00:00
[2022-03-15 10:25:20,343] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.806 seconds
[2022-03-15 10:25:51,118] {processor.py:163} INFO - Started process (PID=1017) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:25:51,119] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:25:51,119] {logging_mixin.py:109} INFO - [2022-03-15 10:25:51,119] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:25:51,629] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:25:51,905] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:25:51,911] {logging_mixin.py:109} INFO - [2022-03-15 10:25:51,911] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:25:51,921] {logging_mixin.py:109} INFO - [2022-03-15 10:25:51,921] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:25:51,929] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.813 seconds
[2022-03-15 10:26:22,052] {processor.py:163} INFO - Started process (PID=1088) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:26:22,054] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:26:22,054] {logging_mixin.py:109} INFO - [2022-03-15 10:26:22,054] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:26:22,618] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:26:22,967] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:26:22,975] {logging_mixin.py:109} INFO - [2022-03-15 10:26:22,974] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:26:22,995] {logging_mixin.py:109} INFO - [2022-03-15 10:26:22,995] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:26:23,023] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.974 seconds
[2022-03-15 10:26:53,734] {processor.py:163} INFO - Started process (PID=1151) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:26:53,734] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:26:53,735] {logging_mixin.py:109} INFO - [2022-03-15 10:26:53,735] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:26:54,259] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:26:54,528] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:26:54,535] {logging_mixin.py:109} INFO - [2022-03-15 10:26:54,535] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:26:54,548] {logging_mixin.py:109} INFO - [2022-03-15 10:26:54,548] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:26:54,561] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.829 seconds
[2022-03-15 10:27:25,375] {processor.py:163} INFO - Started process (PID=1223) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:27:25,376] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:27:25,377] {logging_mixin.py:109} INFO - [2022-03-15 10:27:25,377] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:27:25,988] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:27:26,267] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:27:26,273] {logging_mixin.py:109} INFO - [2022-03-15 10:27:26,273] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:27:26,284] {logging_mixin.py:109} INFO - [2022-03-15 10:27:26,284] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:27:26,298] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.926 seconds
[2022-03-15 10:27:57,007] {processor.py:163} INFO - Started process (PID=1285) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:27:57,008] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:27:57,008] {logging_mixin.py:109} INFO - [2022-03-15 10:27:57,008] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:27:57,510] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:27:57,763] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:27:57,768] {logging_mixin.py:109} INFO - [2022-03-15 10:27:57,768] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:27:57,779] {logging_mixin.py:109} INFO - [2022-03-15 10:27:57,779] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:27:57,792] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.787 seconds
[2022-03-15 10:28:28,517] {processor.py:163} INFO - Started process (PID=1357) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:28:28,519] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:28:28,520] {logging_mixin.py:109} INFO - [2022-03-15 10:28:28,519] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:28:29,026] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:28:29,280] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:28:29,286] {logging_mixin.py:109} INFO - [2022-03-15 10:28:29,286] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:28:29,299] {logging_mixin.py:109} INFO - [2022-03-15 10:28:29,298] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:28:29,312] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.797 seconds
[2022-03-15 10:29:00,110] {processor.py:163} INFO - Started process (PID=1420) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:29:00,111] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:29:00,112] {logging_mixin.py:109} INFO - [2022-03-15 10:29:00,112] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:29:00,599] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:29:00,865] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:29:00,871] {logging_mixin.py:109} INFO - [2022-03-15 10:29:00,870] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:29:00,882] {logging_mixin.py:109} INFO - [2022-03-15 10:29:00,882] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:29:00,895] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.786 seconds
[2022-03-15 10:29:31,747] {processor.py:163} INFO - Started process (PID=1492) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:29:31,748] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:29:31,748] {logging_mixin.py:109} INFO - [2022-03-15 10:29:31,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:29:32,347] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:29:32,702] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:29:32,713] {logging_mixin.py:109} INFO - [2022-03-15 10:29:32,713] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:29:32,731] {logging_mixin.py:109} INFO - [2022-03-15 10:29:32,731] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:29:32,751] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 1.007 seconds
[2022-03-15 10:30:03,148] {processor.py:163} INFO - Started process (PID=1557) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:30:03,150] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:30:03,150] {logging_mixin.py:109} INFO - [2022-03-15 10:30:03,150] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:30:03,662] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:30:03,916] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:30:03,923] {logging_mixin.py:109} INFO - [2022-03-15 10:30:03,923] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:30:03,934] {logging_mixin.py:109} INFO - [2022-03-15 10:30:03,934] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:30:03,947] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.802 seconds
[2022-03-15 10:30:34,798] {processor.py:163} INFO - Started process (PID=1628) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:30:34,800] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:30:34,800] {logging_mixin.py:109} INFO - [2022-03-15 10:30:34,800] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:30:35,338] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:30:35,618] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:30:35,628] {logging_mixin.py:109} INFO - [2022-03-15 10:30:35,628] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:30:35,646] {logging_mixin.py:109} INFO - [2022-03-15 10:30:35,646] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:30:35,660] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.865 seconds
[2022-03-15 10:31:06,465] {processor.py:163} INFO - Started process (PID=1692) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:31:06,466] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:31:06,466] {logging_mixin.py:109} INFO - [2022-03-15 10:31:06,466] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:31:06,953] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:31:07,197] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:31:07,203] {logging_mixin.py:109} INFO - [2022-03-15 10:31:07,202] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:31:07,213] {logging_mixin.py:109} INFO - [2022-03-15 10:31:07,213] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:31:07,221] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.758 seconds
[2022-03-15 10:31:38,090] {processor.py:163} INFO - Started process (PID=1763) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:31:38,091] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:31:38,092] {logging_mixin.py:109} INFO - [2022-03-15 10:31:38,092] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:31:38,632] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:31:38,930] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:31:38,940] {logging_mixin.py:109} INFO - [2022-03-15 10:31:38,939] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:31:38,955] {logging_mixin.py:109} INFO - [2022-03-15 10:31:38,955] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:31:38,969] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.881 seconds
[2022-03-15 10:32:09,700] {processor.py:163} INFO - Started process (PID=1826) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:32:09,701] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:32:09,701] {logging_mixin.py:109} INFO - [2022-03-15 10:32:09,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:32:10,179] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:32:10,423] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:32:10,429] {logging_mixin.py:109} INFO - [2022-03-15 10:32:10,429] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:32:10,440] {logging_mixin.py:109} INFO - [2022-03-15 10:32:10,439] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:32:10,453] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.754 seconds
[2022-03-15 10:32:41,319] {processor.py:163} INFO - Started process (PID=1898) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:32:41,321] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:32:41,321] {logging_mixin.py:109} INFO - [2022-03-15 10:32:41,321] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:32:41,864] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:32:42,132] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:32:42,138] {logging_mixin.py:109} INFO - [2022-03-15 10:32:42,138] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:32:42,149] {logging_mixin.py:109} INFO - [2022-03-15 10:32:42,149] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:32:42,161] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.844 seconds
[2022-03-15 10:33:12,966] {processor.py:163} INFO - Started process (PID=1960) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:33:12,967] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:33:12,967] {logging_mixin.py:109} INFO - [2022-03-15 10:33:12,967] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:33:13,421] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:33:13,668] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:33:13,674] {logging_mixin.py:109} INFO - [2022-03-15 10:33:13,674] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:33:13,684] {logging_mixin.py:109} INFO - [2022-03-15 10:33:13,684] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:33:13,698] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.734 seconds
[2022-03-15 10:33:44,502] {processor.py:163} INFO - Started process (PID=2031) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:33:44,504] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:33:44,504] {logging_mixin.py:109} INFO - [2022-03-15 10:33:44,504] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:33:45,016] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:33:45,270] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:33:45,276] {logging_mixin.py:109} INFO - [2022-03-15 10:33:45,276] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:33:45,286] {logging_mixin.py:109} INFO - [2022-03-15 10:33:45,286] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:33:45,300] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.800 seconds
[2022-03-15 10:34:16,057] {processor.py:163} INFO - Started process (PID=2096) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:16,058] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:34:16,058] {logging_mixin.py:109} INFO - [2022-03-15 10:34:16,058] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:16,633] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:34:16,901] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:16,907] {logging_mixin.py:109} INFO - [2022-03-15 10:34:16,907] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:34:16,918] {logging_mixin.py:109} INFO - [2022-03-15 10:34:16,918] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:34:16,925] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.870 seconds
[2022-03-15 10:34:22,547] {processor.py:163} INFO - Started process (PID=2143) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:22,549] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:34:22,549] {logging_mixin.py:109} INFO - [2022-03-15 10:34:22,549] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:23,088] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:34:23,346] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:23,352] {logging_mixin.py:109} INFO - [2022-03-15 10:34:23,352] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:34:23,362] {logging_mixin.py:109} INFO - [2022-03-15 10:34:23,362] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:34:23,376] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.831 seconds
[2022-03-15 10:34:54,109] {processor.py:163} INFO - Started process (PID=2208) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:54,110] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:34:54,111] {logging_mixin.py:109} INFO - [2022-03-15 10:34:54,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:54,627] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:34:54,902] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:34:54,909] {logging_mixin.py:109} INFO - [2022-03-15 10:34:54,908] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:34:54,920] {logging_mixin.py:109} INFO - [2022-03-15 10:34:54,920] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:34:54,928] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.821 seconds
[2022-03-15 10:35:24,959] {processor.py:163} INFO - Started process (PID=2279) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:35:24,960] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:35:24,960] {logging_mixin.py:109} INFO - [2022-03-15 10:35:24,960] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:35:25,473] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:35:25,776] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:35:25,785] {logging_mixin.py:109} INFO - [2022-03-15 10:35:25,785] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:35:25,804] {logging_mixin.py:109} INFO - [2022-03-15 10:35:25,804] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:35:25,814] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.857 seconds
[2022-03-15 10:35:56,509] {processor.py:163} INFO - Started process (PID=2341) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:35:56,511] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:35:56,511] {logging_mixin.py:109} INFO - [2022-03-15 10:35:56,511] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:35:56,981] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:35:57,235] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:35:57,241] {logging_mixin.py:109} INFO - [2022-03-15 10:35:57,241] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:35:57,252] {logging_mixin.py:109} INFO - [2022-03-15 10:35:57,252] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:35:57,260] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.753 seconds
[2022-03-15 10:36:28,086] {processor.py:163} INFO - Started process (PID=2412) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:36:28,087] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:36:28,088] {logging_mixin.py:109} INFO - [2022-03-15 10:36:28,088] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:36:28,628] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:36:28,902] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:36:28,908] {logging_mixin.py:109} INFO - [2022-03-15 10:36:28,907] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:36:28,918] {logging_mixin.py:109} INFO - [2022-03-15 10:36:28,918] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:36:28,926] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.842 seconds
[2022-03-15 10:36:58,978] {processor.py:163} INFO - Started process (PID=2475) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:36:58,979] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:36:58,980] {logging_mixin.py:109} INFO - [2022-03-15 10:36:58,980] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:36:59,452] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:36:59,707] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:36:59,713] {logging_mixin.py:109} INFO - [2022-03-15 10:36:59,712] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:36:59,723] {logging_mixin.py:109} INFO - [2022-03-15 10:36:59,723] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:36:59,736] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.761 seconds
[2022-03-15 10:37:30,574] {processor.py:163} INFO - Started process (PID=2547) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:37:30,574] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:37:30,575] {logging_mixin.py:109} INFO - [2022-03-15 10:37:30,575] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:37:31,089] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:37:31,351] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:37:31,359] {logging_mixin.py:109} INFO - [2022-03-15 10:37:31,359] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:37:31,373] {logging_mixin.py:109} INFO - [2022-03-15 10:37:31,373] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:37:31,388] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.817 seconds
[2022-03-15 10:38:01,566] {processor.py:163} INFO - Started process (PID=2610) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:38:01,568] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:38:01,568] {logging_mixin.py:109} INFO - [2022-03-15 10:38:01,568] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:38:02,027] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:38:02,276] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:38:02,282] {logging_mixin.py:109} INFO - [2022-03-15 10:38:02,281] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:38:02,292] {logging_mixin.py:109} INFO - [2022-03-15 10:38:02,292] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:38:02,304] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.741 seconds
[2022-03-15 10:38:32,729] {processor.py:163} INFO - Started process (PID=2681) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:38:32,730] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:38:32,731] {logging_mixin.py:109} INFO - [2022-03-15 10:38:32,731] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:38:33,265] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:38:33,549] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:38:33,555] {logging_mixin.py:109} INFO - [2022-03-15 10:38:33,554] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:38:33,566] {logging_mixin.py:109} INFO - [2022-03-15 10:38:33,566] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:38:33,580] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.852 seconds
[2022-03-15 10:39:03,843] {processor.py:163} INFO - Started process (PID=2743) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:39:03,845] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:39:03,845] {logging_mixin.py:109} INFO - [2022-03-15 10:39:03,845] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:39:04,330] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:39:04,583] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:39:04,589] {logging_mixin.py:109} INFO - [2022-03-15 10:39:04,588] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:39:04,600] {logging_mixin.py:109} INFO - [2022-03-15 10:39:04,600] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:39:04,612] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.771 seconds
[2022-03-15 10:39:34,946] {processor.py:163} INFO - Started process (PID=2807) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:39:34,947] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:39:34,948] {logging_mixin.py:109} INFO - [2022-03-15 10:39:34,947] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:39:35,492] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:39:35,774] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:39:35,780] {logging_mixin.py:109} INFO - [2022-03-15 10:39:35,780] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:39:35,793] {logging_mixin.py:109} INFO - [2022-03-15 10:39:35,793] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:39:35,806] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.863 seconds
[2022-03-15 10:40:05,848] {processor.py:163} INFO - Started process (PID=2876) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:40:05,849] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:40:05,849] {logging_mixin.py:109} INFO - [2022-03-15 10:40:05,849] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:40:06,373] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:40:06,638] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:40:06,645] {logging_mixin.py:109} INFO - [2022-03-15 10:40:06,644] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:40:06,655] {logging_mixin.py:109} INFO - [2022-03-15 10:40:06,655] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:40:06,668] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.822 seconds
[2022-03-15 10:40:37,346] {processor.py:163} INFO - Started process (PID=2938) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:40:37,347] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:40:37,347] {logging_mixin.py:109} INFO - [2022-03-15 10:40:37,347] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:40:37,890] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:40:38,161] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:40:38,168] {logging_mixin.py:109} INFO - [2022-03-15 10:40:38,168] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:40:38,179] {logging_mixin.py:109} INFO - [2022-03-15 10:40:38,179] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:40:38,200] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.856 seconds
[2022-03-15 10:41:08,248] {processor.py:163} INFO - Started process (PID=3009) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:41:08,250] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:41:08,250] {logging_mixin.py:109} INFO - [2022-03-15 10:41:08,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:41:08,823] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:41:09,113] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:41:09,119] {logging_mixin.py:109} INFO - [2022-03-15 10:41:09,119] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:41:09,131] {logging_mixin.py:109} INFO - [2022-03-15 10:41:09,131] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:41:09,140] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.893 seconds
[2022-03-15 10:41:39,873] {processor.py:163} INFO - Started process (PID=3071) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:41:39,874] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:41:39,874] {logging_mixin.py:109} INFO - [2022-03-15 10:41:39,874] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:41:40,372] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:41:40,620] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:41:40,626] {logging_mixin.py:109} INFO - [2022-03-15 10:41:40,626] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:41:40,637] {logging_mixin.py:109} INFO - [2022-03-15 10:41:40,637] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:41:40,646] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.775 seconds
[2022-03-15 10:42:10,918] {processor.py:163} INFO - Started process (PID=3143) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:42:10,919] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:42:10,920] {logging_mixin.py:109} INFO - [2022-03-15 10:42:10,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:42:11,421] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:42:11,697] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:42:11,703] {logging_mixin.py:109} INFO - [2022-03-15 10:42:11,703] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:42:11,715] {logging_mixin.py:109} INFO - [2022-03-15 10:42:11,715] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:42:11,731] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.815 seconds
[2022-03-15 10:42:41,823] {processor.py:163} INFO - Started process (PID=3204) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:42:41,824] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:42:41,825] {logging_mixin.py:109} INFO - [2022-03-15 10:42:41,825] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:42:42,344] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:42:42,619] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:42:42,625] {logging_mixin.py:109} INFO - [2022-03-15 10:42:42,625] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:42:42,636] {logging_mixin.py:109} INFO - [2022-03-15 10:42:42,636] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:42:42,645] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.824 seconds
[2022-03-15 10:43:13,039] {processor.py:163} INFO - Started process (PID=3276) to work on /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:43:13,040] {processor.py:642} INFO - Processing file /opt/airflow/dags/load_snowflake.py for tasks to queue
[2022-03-15 10:43:13,040] {logging_mixin.py:109} INFO - [2022-03-15 10:43:13,040] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:43:13,568] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97 UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<3.1.0,>=3.0.0; extra == "pandas"'
[2022-03-15 10:43:13,838] {processor.py:654} INFO - DAG(s) dict_keys(['example_snowflake']) retrieved from /opt/airflow/dags/load_snowflake.py
[2022-03-15 10:43:13,844] {logging_mixin.py:109} INFO - [2022-03-15 10:43:13,844] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-15 10:43:13,858] {logging_mixin.py:109} INFO - [2022-03-15 10:43:13,858] {dag.py:2937} INFO - Setting next_dagrun for example_snowflake to 2022-03-15T10:25:20.328941+00:00
[2022-03-15 10:43:13,873] {processor.py:171} INFO - Processing /opt/airflow/dags/load_snowflake.py took 0.836 seconds
